// Regenerates src/server/printer/escpos/codepages.ts from iconv-lite tables.
// Usage: node scripts/gen-codepages.ts
import iconv from 'iconv-lite';
import { writeFileSync } from 'node:fs';

// Epson `ESC t n` character code tables (single-byte ones we can map to Unicode).
const EPSON: Record<number, string> = {
  0: 'cp437', 2: 'cp850', 3: 'cp860', 4: 'cp863', 5: 'cp865', 11: 'cp851', 12: 'cp853', 13: 'cp857',
  14: 'cp737', 15: 'iso8859-7', 16: 'windows1252', 17: 'cp866', 18: 'cp852', 19: 'cp858',
  32: 'cp720', 33: 'cp775', 34: 'cp855', 35: 'cp861', 36: 'cp862', 37: 'cp864', 38: 'cp869',
  39: 'iso8859-2', 40: 'iso8859-15', 41: 'cp1098', 45: 'windows1250', 46: 'windows1251', 47: 'windows1253',
  48: 'windows1254', 49: 'windows1255', 50: 'windows1256', 51: 'windows1257', 52: 'windows1258',
};

// Positions where Epson's table differs from iconv-lite's (IBM added the euro to PC857 at 0xD5).
const OVERRIDES: Record<number, Record<number, string>> = { 13: { 0xd5: '€' } };

const high = Buffer.from(Array.from({ length: 128 }, (_, i) => 0x80 + i));
let out = '// Generated by scripts/gen-codepages.ts from iconv-lite. Do not edit.\n';
out += '// Upper half (0x80-0xFF) of each Epson `ESC t n` table; the lower half is ASCII.\n';
out += 'export const CODE_PAGES: Record<number, { name: string; high: string }> = {\n';
for (const [n, name] of Object.entries(EPSON)) {
  if (!iconv.encodingExists(name)) { console.error(`skip ${n} ${name}`); continue; }
  const chars = [...iconv.decode(high, name)].map((c, i) => OVERRIDES[Number(n)]?.[0x80 + i] ?? c).join('');
  if ([...chars].length !== 128) throw new Error(`${name}: expected 128 chars`);
  out += `  ${n}: { name: '${name}', high: ${JSON.stringify(chars)} },\n`;
}
out += '};\n';
writeFileSync(new URL('../src/server/printer/escpos/codepages.ts', import.meta.url), out);
